### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by afidegnum** [BonfaceKilz/ob-elm#17]
Hi, This is Alexander from Ghana, 

is it possible to embed a full elm executable code, and compile it as Js and Html in Org-mode? 

what available approaches do you suggest?

**Comment by BonfaceKilz** [comment]
Ola Alex o/

KOKOU AFIDEGNON ***@***.***> writes:

> Hi, This is Alexander from Ghana, 
>
> is it possible to embed a full elm executable
> code, and compile it as Js and Html in Org-mode?
>
> what available approaches do you suggest? 

First I'd init a project:

#+begin_src elisp :dir ~/elm-test
(async-shell-command "elm init")
#+end_src

I use the "async-shell-command" since the buffer
it generates is "interactive", so you could fill
out Y/N queries if you have to within Emacs.

Next, I'd create the file and "tangle" it:

#+begin_src elm :tangle ~/elm-test/src/Main.elm
-- Body of elm src files
#+end_src

To tangle do "C-u M-x org-babel-tangle". Tangling
basically tells org to put the contents of that
source file to org. If you want to get contents
back from a file, consider looking at the
org-tanglesync package.

Now that you have things tangled, you could run
the reactor:

#+begin_src elisp :dir ~/elm-test
(async-shell-command "elm make src/Main.elm" "*ELM-MAKE*")
#+end_src

I hope you get the gist. 

You can't do this with ob-elm though. It was
decided to only run elm src from org, the same way
you'd run some other scripting language like
Python...

HTH'ed!

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by afidegnum** [comment]
Thanks for the hint, I will apply that. I'm happy to chat with an emacs/elm enthusiast from Kenya, we can exchange contacts for further discussions/socialization if you don't mind.

**Comment by BonfaceKilz** [comment]
KOKOU AFIDEGNON ***@***.***> writes:

> Thanks for the hint, I will apply that. I'm happy
> to chat with an emacs/elm enthusiast from Kenya,
> we can exchange contacts for further
> discussions/socialization if you don't mind.


Great! I've become more inclined to lisp-like
languages nowadays! But I'm glad to talk about
these things. You could reach out to me vis-a-vis
e-mail(find it on my profile) \m/\m/

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by BonfaceKilz** [comment]
@afidegnum my email is: "me [at] bonfacemunyoki [dot] com"
